apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task
spec:
  params:
    - name: header
      description: The event header
    - name: body
      description: The event body
  steps:
  - name: hello-world
    image: hello-world

