apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task
spec:
  params:
    - name: header
      description: The event header
    - name: body
      description: The event body
  workspaces:
  - name: pipeline
  steps:
  - name: print-event
    env:
      - name: HEADER
        value: $(params.header)
      - name: BODY
        value: $(params.body)
    image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.0
    command: ["/bin/sh", "-c"]
    args:
    - env;
      ls -al /opt/properties;
      ls -al /workspace/pipeline;
      cat /opt/toolchain/toolchain.json | jq .;
    volumeMounts:
    - name: properties
      mountPath: "/opt/properties"
    - name: toolchain
      mountPath: "/opt/toolchain"
  volumes:
  - name: properties
    projected:
      sources:
      - configMap:
          name: default-properties
          optional: true
      - configMap:
          name: environment-properties
          optional: true
      - secret:
          name: secure-properties
          optional: true
  - name: toolchain
    configMap:
      name: toolchain
      optional: true
  