apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task
spec:
  params:
    - name: header
      description: The event header
    - name: body
      description: The event body
    - name: event
      description: The event body
  steps:
  - name: print-event
    env:
      - name: HEADER
        value: $(params.header)
      - name: BODY
        value: $(params.body)
      - name: EVENT
        value: $(params.event)
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - env;
      ls -al /opt/environment-properties;
      ls -al /opt/secure-properties;
      cat /opt/secure-properties/*;
    volumeMounts:
    - name: environment-properties
      mountPath: "/opt/environment-properties"
    - name: secure-properties
      mountPath: "/opt/secure-properties"
  volumes:
  - name: environment-properties
    configMap:
      name: environment-properties
      optional: true
  - name: secure-properties
    secret:
      secretName: secure-properties
      optional: true
  