apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task
spec:
  params:
    - name: header
      description: The event header
    - name: body
      description: The event body
  workspaces:
  - name: pipeline
  steps:
  - name: print-event
    env:
      - name: HEADER
        value: $(params.header)
      - name: BODY
        value: $(params.body)
    image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.0
    command: ["/bin/sh", "-c"]
    args:
    - env;
      source /workspace/scripts/git-auth.sh xyzzy
      #ls -al /workspace/properties;
      #ls -al /workspace/pipeline;
      #cat /workspace/toolchain.json | jq .;
    volumeMounts:
    - name: properties
      mountPath: "/workspace/properties"
    - name: toolchain
      mountPath: "/workspace/toolchain.json"
      subPath: toolchain.json
    - name: scripts
      mountPath: "/workspace/scripts"
  volumes:
  - name: properties
    projected:
      sources:
      - configMap:
          name: default-properties
          optional: true
      - configMap:
          name: environment-properties
          optional: true
      - secret:
          name: secure-properties
          optional: true
  - name: toolchain
    configMap:
      name: toolchain
  - name: scripts
    configMap:
      name: scripts
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task2
spec:
  workspaces:
  - name: pipeline
  steps:
  - name: private-alpine
    image: us.icr.io/skaegi/buildkit-testing:20
    command: ["/bin/sh", "-c"]
    args:
    - ls -al /workspace/pipeline;