apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-template
spec:
  params:
  - name: header
    description: The event header
  - name: body
    description: The event body
  - name: dockerconfigjson
    default: '{"auths":{}}'
  resourcetemplates:
  - apiVersion: v1
    kind: Secret
    type: kubernetes.io/dockerconfigjson
    metadata:
      name: pipeline-pullsecret
    stringData:
      .dockerconfigjson: $(tt.params.dockerconfigjson)
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: pipelinerun-
    spec:
      pipelineRef:
        name: pipeline
      params:
      - name: header
        value: $(tt.params.header)
      - name: body
        value: $(tt.params.body)
      podTemplate:
        imagePullSecrets:
        - name: pipeline-pullsecret
      workspaces:
          - name: pipeline-ws
            persistentVolumeClaim:
              claimName: pipelinerun-pvc

